# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yhPF2YfLq8K5vllMeYx7FidTtzhSIj62
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from google.colab import files
from sklearn.model_selection import train_test_split, ParameterGrid
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

uploaded = files.upload()

df = pd.read_csv("water_potability.csv")

print("Dataset shape:", df.shape)
display(df.head())
display(df.describe())

missing_table = pd.DataFrame({
    "Missing Values": df.isnull().sum(),
    "Missing Percentage (%)": df.isnull().mean() * 100
})
display(missing_table)

potability_table = pd.DataFrame({
    "Count": df["Potability"].value_counts(),
    "Percentage (%)": df["Potability"].value_counts(normalize=True) * 100
})
display(potability_table)

features = df.drop(columns=["Potability"]).columns

for col in features:
    plt.figure(figsize=(6, 4))
    plt.hist(df[col].dropna(), bins=30)
    plt.title(f"Histogram of {col}")
    plt.xlabel(col)
    plt.ylabel("Frequency")
    plt.show()

plt.figure(figsize=(5, 4))
df["Potability"].value_counts().sort_index().plot(kind="bar")
plt.title("Distribution of Potability")
plt.xlabel("Potability")
plt.ylabel("Count")
plt.xticks(ticks=[0, 1], labels=["Not Potable", "Potable"], rotation=0)
plt.show()

ph_df = df.dropna(subset=["ph"]).copy()

def ph_category(ph):
    if ph < 6.5:
        return "pH < 6.5"
    elif ph <= 8.5:
        return "6.5 <= pH <= 8.5"
    else:
        return "pH > 8.5"

ph_df["pH_Category"] = ph_df["ph"].apply(ph_category)

ph_potability_percentages = pd.crosstab(
    ph_df["pH_Category"],
    ph_df["Potability"],
    normalize="index"
) * 100

ph_potability_percentages.columns = ["Not Potable (%)", "Potable (%)"]
display(ph_potability_percentages)

ph_potability_counts = pd.crosstab(ph_df["pH_Category"], ph_df["Potability"])
display(ph_potability_counts)

plt.figure(figsize=(8, 6))

plt.scatter(
    df[df["Potability"] == 1]["ph"],
    df[df["Potability"] == 1]["Chloramines"],
    label="Potable",
    alpha=0.6
)

plt.scatter(
    df[df["Potability"] == 0]["ph"],
    df[df["Potability"] == 0]["Chloramines"],
    label="Not Potable",
    alpha=0.6
)

plt.axvline(x=6.5, linestyle="--", label="pH = 6.5")
plt.axvline(x=8.5, linestyle="--", label="pH = 8.5")
plt.axhline(y=4, linestyle="--", label="Chloramines = 4 ppm")

plt.title("pH vs Chloramines by Potability")
plt.xlabel("pH")
plt.ylabel("Chloramines")
plt.legend()
plt.show()

df_filled = df.copy()

for col in df_filled.columns:
    if df_filled[col].isnull().sum() > 0:
        df_filled[col] = df_filled[col].fillna(df_filled[col].mean())

display(df_filled.isnull().sum())

X = df_filled.drop(columns=["Potability"]).values
y = df_filled["Potability"].values

feature_names = df_filled.drop(columns=["Potability"]).columns

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.30,
    random_state=0
)

print("Training examples:", X_train.shape[0])
print("Test examples:", X_test.shape[0])

dt = DecisionTreeClassifier(random_state=0)
dt.fit(X_train, y_train)

y_train_pred = dt.predict(X_train)
y_test_pred = dt.predict(X_test)

print("Decision Tree Train Accuracy:", accuracy_score(y_train, y_train_pred))
print("Decision Tree Test Accuracy:", accuracy_score(y_test, y_test_pred))
print(classification_report(y_test, y_test_pred))

param_grid_dt = {
    "criterion": ["gini", "entropy"],
    "max_depth": [None, 3, 5],
    "min_samples_split": [2, 5],
    "min_samples_leaf": [1, 2],
    "max_features": [None, "sqrt"],
    "ccp_alpha": [0, 0.01]
}

results_dt = []

for params in ParameterGrid(param_grid_dt):
    model = DecisionTreeClassifier(random_state=0, **params)
    model.fit(X_train, y_train)

    train_pred = model.predict(X_train)
    test_pred = model.predict(X_test)

    results_dt.append({
        **params,
        "train_acc": accuracy_score(y_train, train_pred),
        "test_acc": accuracy_score(y_test, test_pred)
    })

results_dt_df = pd.DataFrame(results_dt).sort_values(by="test_acc", ascending=False)
display(results_dt_df)

def clean_params(params):
    params = dict(params)

    if "max_depth" in params:
        if pd.isna(params["max_depth"]):
            params["max_depth"] = None
        else:
            params["max_depth"] = int(params["max_depth"])

    if "min_samples_split" in params:
        params["min_samples_split"] = int(params["min_samples_split"])

    if "min_samples_leaf" in params:
        params["min_samples_leaf"] = int(params["min_samples_leaf"])

    if "n_estimators" in params:
        params["n_estimators"] = int(params["n_estimators"])

    if "ccp_alpha" in params:
        params["ccp_alpha"] = float(params["ccp_alpha"])

    return params

best_depth3 = results_dt_df[results_dt_df["max_depth"] == 3].sort_values(
    by="test_acc",
    ascending=False
).iloc[0]

display(best_depth3)

best_depth3_params = best_depth3.drop(["train_acc", "test_acc"]).to_dict()
best_depth3_params = clean_params(best_depth3_params)

best_depth3_tree = DecisionTreeClassifier(
    random_state=0,
    **best_depth3_params
)

best_depth3_tree.fit(X_train, y_train)

plt.figure(figsize=(24, 12))
plot_tree(
    best_depth3_tree,
    feature_names=feature_names,
    class_names=["Not Potable", "Potable"],
    filled=True,
    rounded=True,
    fontsize=10
)
plt.title("Best Decision Tree with max_depth = 3")
plt.show()

best_dt = results_dt_df.iloc[0]
display(best_dt)

best_dt_params = best_dt.drop(["train_acc", "test_acc"]).to_dict()
best_dt_params = clean_params(best_dt_params)

best_tree = DecisionTreeClassifier(
    random_state=0,
    **best_dt_params
)

best_tree.fit(X_train, y_train)

importance_df = pd.DataFrame({
    "Feature": feature_names,
    "Importance": best_tree.feature_importances_
}).sort_values(by="Importance", ascending=False)

display(importance_df)

plt.figure(figsize=(10, 5))
plt.bar(importance_df["Feature"], importance_df["Importance"])
plt.title("Feature Importance - Best Decision Tree")
plt.xlabel("Feature")
plt.ylabel("Importance")
plt.xticks(rotation=45)
plt.show()

top_5_features = importance_df.head(5)
display(top_5_features)

param_grid_rf = {
    "n_estimators": [50, 100, 200],
    "criterion": ["gini", "entropy"],
    "max_depth": [None, 3, 5],
    "min_samples_split": [2, 5],
    "min_samples_leaf": [1, 2],
    "max_features": [None, "sqrt"],
    "ccp_alpha": [0, 0.01]
}

results_rf = []

for params in ParameterGrid(param_grid_rf):
    model = RandomForestClassifier(
        random_state=0,
        n_jobs=-1,
        **params
    )

    model.fit(X_train, y_train)

    train_pred = model.predict(X_train)
    test_pred = model.predict(X_test)

    results_rf.append({
        **params,
        "train_acc": accuracy_score(y_train, train_pred),
        "test_acc": accuracy_score(y_test, test_pred)
    })

results_rf_df = pd.DataFrame(results_rf).sort_values(by="test_acc", ascending=False)
display(results_rf_df)

best_rf = results_rf_df.iloc[0]
display(best_rf)

best_rf_params = best_rf.drop(["train_acc", "test_acc"]).to_dict()
best_rf_params = clean_params(best_rf_params)

best_rf_model = RandomForestClassifier(
    random_state=0,
    n_jobs=-1,
    **best_rf_params
)

best_rf_model.fit(X_train, y_train)

rf_train_pred = best_rf_model.predict(X_train)
rf_test_pred = best_rf_model.predict(X_test)

print("Best Random Forest Train Accuracy:", accuracy_score(y_train, rf_train_pred))
print("Best Random Forest Test Accuracy:", accuracy_score(y_test, rf_test_pred))
print(classification_report(y_test, rf_test_pred))

rf_importance_df = pd.DataFrame({
    "Feature": feature_names,
    "Importance": best_rf_model.feature_importances_
}).sort_values(by="Importance", ascending=False)

display(rf_importance_df)

plt.figure(figsize=(10, 5))
plt.bar(rf_importance_df["Feature"], rf_importance_df["Importance"])
plt.title("Feature Importance - Best Random Forest")
plt.xlabel("Feature")
plt.ylabel("Importance")
plt.xticks(rotation=45)
plt.show()